### PR TITLE
added 1 ressource under Miscellaneous

### PR DESCRIPTION
**Pull request by dattvidc**
I think a heading with computer science stuff could be useful.

### CODE REVIEW

**Comment by dattvidc** [comment]
I hope I did this right @BycorSanchez , if not feel free to delete pull request. I am thinking about adding a bunch of more ressources, but wanted to test the waters with one.

**Comment by BycorSanchez** [comment]
Thanks @dattvidc. 
It's a really good resource, just add it to README.md file as well using `*(name)[url]` format.

**Comment by BycorSanchez** [comment]
I'll consider a new computer science category. Generally I create a new section/category when there are at least two related resources.

**Comment by dattvidc** [comment]
file updated.

**Comment by BycorSanchez** [comment]
List updated

**Comment by dattvidc** [comment]
;)

**Pull request merged**
